apiVersion: v1
kind: ConfigMap
metadata:
  name: doctor-service-config
data:
  EUREKA_SERVER_ADDRESS: "http://eureka-0.eureka.healthcare-app.svc.cluster.local:8761/eureka/"
  SPRING_APPLICATION_NAME: "doctor-service" 