apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service-app
  labels:
    app: doctor-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-service-app
  template:
    metadata:
      labels:
        app: doctor-service-app
    spec:
      containers:
        - name: doctor-service-app
          image: bhavya28122251/doctor-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: EUREKA_SERVER_ADDRESS

            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SPRING_DATASOURCE_DRIVER_CLASS_NAME

            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO

            - name: SPRING_JPA_SHOW_SQL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SPRING_JPA_SHOW_SQL

            - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL

            - name: SPRING_JPA_DATABASE_PLATFORM
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SPRING_JPA_DATABASE_PLATFORM

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
