apiVersion: v1
kind: Service
metadata:
  name: doctor-service-svc
  labels:
    app: doctor-service-app
spec:
  selector:
    app: doctor-service-app
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
  type: ClusterIP
