---
- name: Deploy Appointment Service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'appointment-service.yml.j2') | from_yaml_all | list }}"
    namespace: healthcare-app 