---
- name: Create namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: healthcare-app

- name: Create ConfigMap for Eureka
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: eureka-cm
        namespace: healthcare-app
      data:
        eureka_service_address: "{{ eureka_service_address }}"

- name: Create Secret for Docker Registry
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: docker-registry-secret
        namespace: healthcare-app
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ lookup('template', 'docker-config.json.j2') | b64encode }}"

- name: Create Secret for Database
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: db-secret
        namespace: healthcare-app
      type: Opaque
      data:
        username: "{{ db_user | b64encode }}"
        password: "{{ db_password | b64encode }}"
        root-password: "{{ db_root_password | b64encode }}"

- name: Create Secret for JWT
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: jwt-secret
        namespace: healthcare-app
      type: Opaque
      data:
        jwt_secret: "{{ jwt_secret | b64encode }}" 