- name: Deploy Auth Service Components
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
    namespace: healthcare-app
  with_items:
    - ../K8s/microservices/auth-service/config.yml
    - ../K8s/microservices/auth-service/service.yml
    - ../K8s/microservices/auth-service/deployment.yml
    - ../K8s/microservices/auth-service/HPA.yml