---
all:
  hosts:
    k8s_master:
      ansible_host: "{{ k8s_master_ip }}"
      ansible_user: "{{ k8s_master_user }}"
  children:
    kubernetes:
      hosts:
        master:
          ansible_host: "{{ k8s_master_ip }}"
          ansible_user: "{{ k8s_master_user }}"
          ansible_ssh_private_key_file: "{{ ssh_private_key_path }}" 