apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service-app
  labels:
    app: doctor-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-service-app
  template:
    metadata:
      labels:
        app: doctor-service-app
    spec:
      containers:
        - name: doctor-service-app
          image: bhavya28122251/doctor-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SPRING_CLOUD_CONFIG_URI

            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: EUREKA_SERVER_ADDRESS

            

---
apiVersion: v1
kind: Service
metadata:
  name: doctor-service-svc
spec:
  selector:
    app: doctor-service-app
  ports:
    - port: 80
      targetPort: 8083
