apiVersion: v1
kind: ConfigMap
metadata:
  name: doctor-service-config
data:
  EUREKA_SERVER_ADDRESS: "http://eureka-0.eureka.default.svc.cluster.local:8761/eureka/"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service-app
  labels:
    app: doctor-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-service-app
  template:
    metadata:
      labels:
        app: doctor-service-app
    spec:
      containers:
        - name: doctor-service-app
          image: bhavya28122251/doctor-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: doctor-service-config
                  key: EUREKA_SERVER_ADDRESS

---
apiVersion: v1
kind: Service
metadata:
  name: doctor-service-svc
spec:
  selector:
    app: doctor-service-app
  ports:
    - port: 80
      targetPort: 8083
