apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    spec:
      containers:
      - name: mysql
        resources:
          limits:
            memory: 4Gi
            cpu: "2"
          requests:
            memory: 1Gi
            cpu: 500m 