apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service-app
  labels:
    app: appointment-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service-app
  template:
    metadata:
      labels:
        app: appointment-service-app
    spec:
      containers:
        - name: appointment-service-app
          image: bhavya28122251/appointment-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: DOCTOR_SERVICE_URL
              value: "http://doctor-service-svc.healthcare-app.svc.cluster.local:80"
            - name: PATIENT_SERVICE_URL
              value: "http://patient-service-svc.healthcare-app.svc.cluster.local:80"
              
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: EUREKA_SERVER_ADDRESS

            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SPRING_DATASOURCE_DRIVER_CLASS_NAME

            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO

            - name: SPRING_JPA_SHOW_SQL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SPRING_JPA_SHOW_SQL

            - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL

            - name: SPRING_JPA_DATABASE_PLATFORM
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SPRING_JPA_DATABASE_PLATFORM

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8084
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8084
          #   initialDelaySeconds: 15
          #   periodSeconds: 5
          #   failureThreshold: 2
