apiVersion: v1
kind: Service
metadata:
  name: appointment-service-svc
spec:
  selector:
    app: appointment-service-app
  ports:
    - port: 80
      targetPort: 8084
      protocol: TCP
  type: ClusterIP