---
- name: Deploy Healthcare Application
  hosts: kubernetes
  connection: local
  roles:
    - namespace
    - common-config
    - mysql
    - service-registry
    - auth-service
    - patient-service
    - doctor-service
    - appointment-service
    - api-gateway
    - frontend
    - ingress
