- name: Deploy Doctor Service Components
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
    namespace: healthcare-app
  with_items:
    - ../K8s/microservices/doctor-service/service.yml
    - ../K8s/microservices/doctor-service/deployment.yml