- name: Deploy Patient Service
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
    namespace: healthcare-app
  with_items:
    - ../K8s/microservices/patient-service/service.yml
    - ../K8s/microservices/patient-service/deployment.yml

